"""Fetch + self-host the web fonts used by docs/index.html.

Downloads only what the page needs (latin subsets) into docs/assets/fonts/
and regenerates docs/assets/css/fonts.css with local relative URLs.
Run once; the repo then ships fully offline.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "docs" / "assets" / "fonts"
CSS_OUT = ROOT / "docs" / "assets" / "css" / "fonts.css"

UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Space+Mono:ital,wght@0,400;0,700;1,400"
    "&family=Instrument+Serif:ital@0;1&display=swap"
)

# Clash Display (Fontshare, free for commercial use) — latin, 500/600/700
CLASH = {
    500: "https://cdn.fontshare.com/wf/2GQIT54GKQY3JRFTSHS4ARTRNRQISSAA/3CIP5EBHRRHE5FVQU3VFROPUERNDSTDF/JTSL5QESUXATU47LCPUNHZQBDDIWDOSW.woff2",
    600: "https://cdn.fontshare.com/wf/FPDAZ2S6SW4QMSRIIKNNGTPM6VIXYMKO/5HNPQ453FRLIQWV2FNOBUU3FKTDZQVSG/Z3MGHFHX6DCTLQ55LJYRJ5MDCZPMFZU6.woff2",
    700: "https://cdn.fontshare.com/wf/BFBSY7LX5W2U2EROCLVVTQP4VS7S4PC3/IIUX4FGTMD2LK2VWD3RVTAS4SSMUN7B5/53RZKGODFYDW3QHTIL7IPOWTBCSUEZK7.woff2",
}


def fetch(url: str) -> bytes:
    """Download via curl. Python's own TLS stack fails intermittently against
    fonts.gstatic.com on some Windows networks (SSL: UNEXPECTED_EOF_WHILE_READING);
    curl has proven reliable, so shell out to it."""
    out = subprocess.run(
        ["curl", "-sS", "--max-time", "60", "-A", UA, url],
        capture_output=True,
        check=True,
    ).stdout
    if len(out) < 256:
        raise RuntimeError(f"suspiciously small response ({len(out)} B) for {url}")
    return out


def parse_google(raw) -> list:
    """Yield (family, weight, style, subset, url) for every @font-face block."""
    css = raw.decode("utf-8") if isinstance(raw, bytes) else raw
    out = []
    for subset, body in re.findall(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S):
        fam = re.search(r"font-family:\s*'([^']+)'", body)
        wt = re.search(r"font-weight:\s*(\d+)", body)
        st = re.search(r"font-style:\s*(\w+)", body)
        url = re.search(r"url\((https[^)]+)\)", body)
        if not (fam and wt and st and url):
            continue
        out.append((fam.group(1), int(wt.group(1)), st.group(1), subset, url.group(1)))
    return out


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    wanted = {
        ("Space Mono", 400, "normal"): "sm4.woff2",
        ("Space Mono", 700, "normal"): "sm7.woff2",
        ("Instrument Serif", 400, "italic"): "is-it.woff2",
        ("Instrument Serif", 400, "normal"): "is-rg.woff2",
    }

    lines = [
        "/* Self-hosted fonts — no CDN, no network. Generated by scripts/fetch_fonts.py */",
        "/* Clash Display: Fontshare (free for commercial use) */",
    ]

    for wt, url in sorted(CLASH.items()):
        name = f"cd{wt}.woff2"
        (FONT_DIR / name).write_bytes(fetch(url))
        lines += [
            "@font-face {",
            "  font-family: 'Clash Display';",
            f"  src: url('../fonts/{name}') format('woff2');",
            f"  font-weight: {wt};",
            "  font-style: normal;",
            "  font-display: swap;",
            "}",
        ]
        print(f"  clash {wt:>3} -> {name}")

    for fam, wt, st, subset, url in parse_google(fetch(GOOGLE_CSS)):
        if subset != "latin":
            continue
        key = (fam, wt, st)
        if key not in wanted:
            continue
        name = wanted[key]
        (FONT_DIR / name).write_bytes(fetch(url))
        lines += [
            "@font-face {",
            f"  font-family: '{fam}';",
            f"  src: url('../fonts/{name}') format('woff2');",
            f"  font-weight: {wt};",
            f"  font-style: {st};",
            "  font-display: swap;",
            "}",
        ]
        print(f"  {fam:17} {wt:>3} {st:<7} -> {name}")

    CSS_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total = sum(f.stat().st_size for f in FONT_DIR.glob("*.woff2"))
    print(f"\n{len(list(FONT_DIR.glob('*.woff2')))} files, {total / 1024:.0f} KB -> {CSS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
